services:
  bot:
    build: .
    container_name: discordclanker
    restart: unless-stopped
    env_file: .env
    environment:
      - COOKIES_PATH=/app/cookies.txt
    volumes:
      - ./www.youtube.com_cookies.txt:/app/cookies.txt
      - bot_data:/app/data
    networks:
      - internal

volumes:
  bot_data:

networks:
  internal:
    external: true
